name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup python environment
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup poetry
        run: python -m pip install -U poetry

      - name: Install dependencies
        run: poetry install

      - name: Run flake8 and pyright
        run: poetry run task lint

      - name: Test with pytest
        run: poetry run task test
